[workspace]
members = ["packages/backend/*", "packages/frontend/*", "packages/solana-programs/*"]
resolver = "2"

[workspace.package]
description = "groupshop"
edition = "2021"
version = "0.1.0"
license = "MIT"
authors = ["David Komer"]
rust-version = "1.80.0"

[workspace.dependencies]
groupshop-backend-shared = { path = "packages/backend/backend-shared" }
groupshop-frontend-shared = { path = "packages/frontend/frontend-shared" }

# Frontend
dominator = "0.5.38"
futures-signals = "0.3"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.82", features = ["Document", "Element", "HtmlElement", "Location", "Response", "Window"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# WASM utilities
js-sys = "0.3"

# Cloudflare
worker = { version = "0.7.5", features = ["d1", "http"] }

# Solana
pinocchio = {version = "0.11.1", features = ["cpi"]}
solana-program-log = "1.1.0"
